name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9
          standalone: true 

      - name: "Authenticate GitHub Package Registry"
        run: |
          echo "@execlandry:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: "Install dependencies"
        run: pnpm install

      - name: "Run affected tests"
        run: pnpx nx affected --target=test --base=origin/main --head=HEAD
