name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com/"

      - name: "Setup pnpm"
        run: npm install -g pnpm

      - name: "Authenticate GitHub Package Registry"
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: "Install dependencies"
        run: pnpm install

      - name: "Version and Publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ "${{ github.base_ref }}" = "development" ]; then
            npx nx run-many --target=version --all --args="--preid=beta"
          else
            npx nx run-many --target=version --all
          fi

          npx nx run-many --target=publish --all
